format: yamanifest
version: 1.0
---
work/atmosphere/README:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/atmosphere/README
  hashes:
    binhash: f57a720728dd5c5b853f8e987643e7ce
    md5: 7bd64f211428cf0756fc965d7b443501
work/atmosphere/restart_dump.astart:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/atmosphere/restart_dump.astart
  hashes:
    binhash: 7fe3b6a871a05ae7e5e8b911fdcdbf40
    md5: c46e4c9265692579cdca359972bfd3d4
work/atmosphere/um.res.yaml:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/atmosphere/um.res.yaml
  hashes:
    binhash: a53dd6afbe78e47493e06f8be0bd85fa
    md5: 78f26c60a2e2e0336c7acec9bfecd7bf
work/coupler/README:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/coupler/README
  hashes:
    binhash: 3388804d2dae44197e0fde01495629db
    md5: 768ff92e08cd282933f69084ca3d18d2
work/coupler/a2i.nc:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/coupler/a2i.nc
  hashes:
    binhash: b8437c85bbc29062081226eae5fb978e
    md5: 53c917f70f867e37a084672e8a1997db
work/coupler/i2a.nc:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/coupler/i2a.nc
  hashes:
    binhash: 9990cd434a4afbb180bdd0c32fb03020
    md5: a30b12d2709ef6ae6bb40444b1db0ee2
work/coupler/o2i.nc:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/coupler/o2i.nc
  hashes:
    binhash: d9763a791d85ca3e6f5d72df38dd4f17
    md5: 66a4bed2d785d04bf9041e14eb15d87f
work/ice/RESTART/README:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/README
  hashes:
    binhash: f57a720728dd5c5b853f8e987643e7ce
    md5: 7bd64f211428cf0756fc965d7b443501
work/ice/RESTART/cice_in.nml:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/cice_in.nml
  hashes:
    binhash: 964ce13887127b0fca33694842cfe245
    md5: 1576287c82da88ffc4752430100f848e
work/ice/RESTART/ice.restart_file:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/ice.restart_file
  hashes:
    binhash: 1786d94c4f19ac949de1e7bd1fd9f236
    md5: 507c36763937f8f47d5a592c5d24095d
work/ice/RESTART/iced.18500101:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/iced.18500101
  hashes:
    binhash: 634b078d50fc548419b4d35d1c07e8d5
    md5: ca0d4395cfadb19a9b0ab4d07bd25961
work/ice/RESTART/input_ice.nml:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/input_ice.nml
  hashes:
    binhash: c0a592b8720ecff569b5ba9558d38f03
    md5: 48d62b9cbf71fe6373c02005adb58471
work/ice/RESTART/mice.nc:
  copy: true
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ice/mice.nc
  hashes:
    binhash: 24ce8602876ab14e9607f4d4ed192f44
    md5: 0085475b82f3e0876b7be9203538c97a
work/ocean/INPUT/README:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/README
  hashes:
    binhash: 814bf75a649faefd86bf05204f5716a3
    md5: 768ff92e08cd282933f69084ca3d18d2
work/ocean/INPUT/csiro_bgc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/csiro_bgc.res.nc
  hashes:
    binhash: 9df75dc4846b643bc6df4db15bbd5f18
    md5: 0567fdf6be0e1f7da67e3f7aed3e32c0
work/ocean/INPUT/csiro_bgc_sediment.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/csiro_bgc_sediment.res.nc
  hashes:
    binhash: 114b137685fafde1782498e315c94ca6
    md5: d1de12ab9eef3a4ba17113a801f9e6f8
work/ocean/INPUT/ocean_age.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_age.res.nc
  hashes:
    binhash: acc7cafdd3d693816054a945b1d957cc
    md5: b324bd43e343d2b8eb3bd5d9014e1dba
work/ocean/INPUT/ocean_barotropic.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_barotropic.res.nc
  hashes:
    binhash: ee3a20c3240d65ff567338490e796c8f
    md5: 2c65c22e627689dbb99c7e48d198eec6
work/ocean/INPUT/ocean_bih_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_bih_friction.res.nc
  hashes:
    binhash: 3c6788d9d210e103c370f611fbdbadc6
    md5: 6cc40c8d7895bc9bf8d14066e5aa1fbd
work/ocean/INPUT/ocean_density.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_density.res.nc
  hashes:
    binhash: 678f0a30336ab556c2472ef8daa1b28e
    md5: 07cdb0236d303b767ee6fb75ced59785
work/ocean/INPUT/ocean_frazil.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_frazil.res.nc
  hashes:
    binhash: eaf2f2a95d5d1640868c2990d30ac21e
    md5: b6feb3d546146172f7d877f259f412a6
work/ocean/INPUT/ocean_lap_friction.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_lap_friction.res.nc
  hashes:
    binhash: 5407de8b34be3f04cbdeba978699f3f8
    md5: d2c9747a6a51b6edc4e7474b5e424bb3
work/ocean/INPUT/ocean_neutral.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_neutral.res.nc
  hashes:
    binhash: 5c867ea3a0c80623b069ccaadb44d4fe
    md5: ada60736c5cda5f230e0e57cc074f08b
work/ocean/INPUT/ocean_pot_temp.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_pot_temp.res.nc
  hashes:
    binhash: 53983b268dbdd9afa6b7d0d3c4db78be
    md5: f4f55e359da62c16c93bc2b394eb57e1
work/ocean/INPUT/ocean_sbc.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_sbc.res.nc
  hashes:
    binhash: c75e2132ab7182f31f50007ec50ffd16
    md5: 329c77b819420ef9f878fef98818b9bf
work/ocean/INPUT/ocean_sigma_transport.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_sigma_transport.res.nc
  hashes:
    binhash: 4cc6be89635699811f819cb04ef174a2
    md5: fe527a9917d30955d0dc082271c1392f
work/ocean/INPUT/ocean_solo.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_solo.res
  hashes:
    binhash: 3ae0ee4bddf19bb7120ed54353a1f53a
    md5: 2b1c789b3ff6389a05a769a0d0934334
work/ocean/INPUT/ocean_temp_salt.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_temp_salt.res.nc
  hashes:
    binhash: d2dede6c32380e06180101a5c8fe648b
    md5: d59017739edb08299afe542567f73095
work/ocean/INPUT/ocean_thickness.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_thickness.res.nc
  hashes:
    binhash: 162389752d182dbf18c5137b9acfa923
    md5: 67be2b864dcb5e643aa2b80ae44e78ca
work/ocean/INPUT/ocean_tracer.res:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_tracer.res
  hashes:
    binhash: 2629e16aa1c6541121c84b78c47b470b
    md5: 4d105dfe1fba502278db9e80d5ec1dae
work/ocean/INPUT/ocean_velocity.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_velocity.res.nc
  hashes:
    binhash: 25375d5efe4247f5af0e7b81e46b864b
    md5: bc927019d11866a8ae67cb5bd5ddec93
work/ocean/INPUT/ocean_velocity_advection.res.nc:
  fullpath: /g/data/vk83/configurations/inputs/access-esm1p5/modern/historical/restart/ocean/ocean_velocity_advection.res.nc
  hashes:
    binhash: 835cb1239595d73d8839aabbf9e330dd
    md5: 2183be2ef353d129f56688247b0fbf3d
